### ISSUE TITLE
Use cases download failure

### ISSUE THREAD

**Issue by Poorvasisodia** [tvarit-foggy/tvarit.com#452] opened 2020-10-27 05:08 UTC
When we input the information required to download the use cases, the page seems moving, but there is no response
![Use case download failure](https://user-images.githubusercontent.com/73514628/97259318-8ac3e680-1840-11eb-87c2-f60e13cabbaf.png) Link boelow:
https://tvarit.com/optimize-oee-for-steel-and-metal-manufacturing-companies
https://tvarit.com/predictive-maintenance-for-industrial-electric-motors
https://tvarit.com/ai-based-production-solution-for-cable-manufacturing
https://tvarit.com/predictive-quality-for-die-casting-machines

**Comment by Sumeshks29** [comment] 2020-10-28 14:09
Duplicate of #450

**Closed by Sumeshks29** 2020-10-28 14:09 UTC
